{{- if and .Values.postgresql.enabled (and .Values.postgresql.primary.persistence.enabled .Values.postgresql.primary.persistence.dedicatedDisk.enabled) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ required "value for .Values.postgresql.primary.persistence.existingClaim must be present to use a dedicated disk for PostgreSQL" .Values.postgresql.primary.persistence.existingClaim }}
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "32Gi" .Values.postgresql.primary.persistence.size }}
  volumeName: {{ .Values.postgresql.primary.persistence.existingClaim }}
  storageClassName: "managed-csi"
{{- end -}}
